/*
 * generated by Xtext 2.13.0
 */
package it.unimi.di.se.mdp


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MdpDslStandaloneSetup extends MdpDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MdpDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
