/*
 * generated by Xtext 2.13.0
 */
package it.unimi.di.se.mdp.ide

import com.google.inject.Guice
import it.unimi.di.se.mdp.MdpDslRuntimeModule
import it.unimi.di.se.mdp.MdpDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MdpDslIdeSetup extends MdpDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MdpDslRuntimeModule, new MdpDslIdeModule))
	}
	
}
