/*
 * generated by Xtext 2.13.0
 */
package it.unimi.di.se.mdp.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class MdpDslScopeProvider extends AbstractMdpDslScopeProvider {

}
